### ISSUE TITLE
[RPR] Bug where if during enshroud Shadow of Death falls off, combo gets stuck on Slice.

### ISSUE THREAD

**Issue by Dedoooo** [PunishXIV/WrathCombo#67]

**Comment by Kagekazu** [comment]
I can remove it. BUT then I don't want any bug reports about SoD uptime not being optimal. 

Normally it is made so it will do SoD as prio before it enshrouds. 

Since it's a 10% flat dps loss on every skill u do while the buff isn't active, it can be significant for ur hard hitting skills like communio and perfectio.
